---
- name: Configure puppet agent
  hosts: localhost
  become: true

  vars_files:
    - variables.yml

  tasks:
    - name: Set hostname
      hostname:
        name: "{{ certname }}"
      when: certname is defined

    - name: Set date using NTP
      command: ntpdate {{ server }}
      async: 0
      poll: 0
      ignore_errors: true
      when: server is defined

    - name: Copy network config files
      copy:
        src: "{{ item.src }}"
        dest: "/etc/sysconfig/network-scripts/{{ item.dest }}"
        owner: root
        group: root
        mode: '0644'
      with_items:
        - { src: "ifcfg-bond0", dest: "ifcfg-bond0" }
        - { src: "ifcfg-bond1", dest: "ifcfg-bond1" }
        - { src: "ifcfg-eth0", dest: "ifcfg-eth0" }
        - { src: "ifcfg-eth1", dest: "ifcfg-eth1" }
      when: "'ifcfg-bond0' in file_list and 'ifcfg-bond1' in file_list and 'ifcfg-eth0' in file_list and 'ifcfg-eth1' in file_list"

    - name: Copy bond network config files
      copy:
        src: "{{ item.src }}"
        dest: "/etc/sysconfig/network-scripts/{{ item.dest }}"
        owner: root
        group: root
        mode: '0644'
      with_items:
        - { src: "ifcfg-bond0", dest: "ifcfg-bond0" }
        - { src: "ifcfg-bond1", dest: "ifcfg-bond1" }
      when: "'ifcfg-bond0' not in file_list and 'ifcfg-bond1' not in file_list"

    - name: Set bond network config files from variables
      template:
        src: "{{ item }}"
        dest: "/etc/sysconfig/network-scripts/{{ item }}"
        owner: root
        group: root
        mode: '0644'
      with_items:
        - "ifcfg-bond0"
        - "ifcfg-bond1"
      when: "'ifcfg-bond0' not in file_list and 'ifcfg-bond1' not in file_list"

    - name: Restart network services
      service:
        name: network
        state: restarted
      when: "'ifcfg-bond0' in file_list and 'ifcfg-bond1' in file_list and 'ifcfg-eth0' in file_list and 'ifcfg-eth1' in file_list"

    - name: Move files to /tmp if not present
      command: mv /etc/sysconfig/network-scripts/{{ item }} /tmp/
      with_items:
        - "ifcfg-p3p1"
        - "ifcfg-p3p2"
      args:
        creates: "/etc/sysconfig/network-scripts/{{ item }}"
